# Generated by Django 3.2 on 2023-01-04 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
        ('supplier', '0001_initial'),
        ('advance_deposit', '0002_initial'),
        ('customer', '0002_customer_created_by'),
        ('item', '0002_initial'),
        ('log_app', '0001_initial'),
        ('customer_order', '0002_initial'),
        ('party_payment', '0001_initial'),
        ('core_app', '0002_initial'),
        ('user_group', '0001_initial'),
        ('purchase', '0001_initial'),
        ('credit_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loguser',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user_group.customgroup'),
        ),
        migrations.AddField(
            model_name='logsupplier',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='blank= True and null= True', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.country'),
        ),
        migrations.AddField(
            model_name='logsaleprintlog',
            name='sale_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.salemaster'),
        ),
        migrations.AddField(
            model_name='logsalepaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='logsalepaymentdetail',
            name='sale_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.salemaster'),
        ),
        migrations.AddField(
            model_name='logsalemaster',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='null =True', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='logsalemaster',
            name='discount_scheme',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.discountscheme'),
        ),
        migrations.AddField(
            model_name='logsalemaster',
            name='fiscal_session_ad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.fiscalsessionad'),
        ),
        migrations.AddField(
            model_name='logsalemaster',
            name='fiscal_session_bs',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.fiscalsessionbs'),
        ),
        migrations.AddField(
            model_name='logsalemaster',
            name='ref_order_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_order.ordermaster'),
        ),
        migrations.AddField(
            model_name='logsalemaster',
            name='ref_sale_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.salemaster'),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.item'),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='item_category',
            field=models.ForeignKey(blank=True, db_constraint=False, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='packing_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.packingtype'),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='packing_type_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.packingtypedetail'),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='ref_order_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_order.orderdetail'),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchasedetail'),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='ref_sale_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.saledetail'),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='sale_master',
            field=models.ForeignKey(blank=True, db_constraint=False, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.salemaster'),
        ),
        migrations.AddField(
            model_name='logsaleadditionalcharge',
            name='charge_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.additionalchargetype'),
        ),
        migrations.AddField(
            model_name='logsaleadditionalcharge',
            name='sale_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.salemaster'),
        ),
        migrations.AddField(
            model_name='logpurchasepaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='logpurchasepaymentdetail',
            name='purchase_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchasemaster'),
        ),
        migrations.AddField(
            model_name='logpurchaseordermaster',
            name='discount_scheme',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.discountscheme'),
        ),
        migrations.AddField(
            model_name='logpurchaseordermaster',
            name='ref_purchase_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchaseordermaster'),
        ),
        migrations.AddField(
            model_name='logpurchaseordermaster',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supplier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='logpurchaseorderdetail',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.item'),
        ),
        migrations.AddField(
            model_name='logpurchaseorderdetail',
            name='item_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='logpurchaseorderdetail',
            name='packing_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.packingtype'),
        ),
        migrations.AddField(
            model_name='logpurchaseorderdetail',
            name='packing_type_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.packingtypedetail'),
        ),
        migrations.AddField(
            model_name='logpurchaseorderdetail',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchaseordermaster'),
        ),
        migrations.AddField(
            model_name='logpurchaseorderdetail',
            name='ref_purchase_order_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchaseorderdetail'),
        ),
        migrations.AddField(
            model_name='logpurchasemaster',
            name='discount_scheme',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.discountscheme'),
        ),
        migrations.AddField(
            model_name='logpurchasemaster',
            name='fiscal_session_ad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.fiscalsessionad'),
        ),
        migrations.AddField(
            model_name='logpurchasemaster',
            name='fiscal_session_bs',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.fiscalsessionbs'),
        ),
        migrations.AddField(
            model_name='logpurchasemaster',
            name='ref_purchase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchasemaster'),
        ),
        migrations.AddField(
            model_name='logpurchasemaster',
            name='ref_purchase_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchaseordermaster'),
        ),
        migrations.AddField(
            model_name='logpurchasemaster',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supplier null=True', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='logpurchasedetail',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.item'),
        ),
        migrations.AddField(
            model_name='logpurchasedetail',
            name='item_category',
            field=models.ForeignKey(blank=True, db_constraint=False, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='logpurchasedetail',
            name='packing_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.packingtype'),
        ),
        migrations.AddField(
            model_name='logpurchasedetail',
            name='packing_type_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.packingtypedetail'),
        ),
        migrations.AddField(
            model_name='logpurchasedetail',
            name='purchase',
            field=models.ForeignKey(blank=True, db_constraint=False, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchasemaster'),
        ),
        migrations.AddField(
            model_name='logpurchasedetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchasedetail'),
        ),
        migrations.AddField(
            model_name='logpurchasedetail',
            name='ref_purchase_order_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchaseorderdetail'),
        ),
        migrations.AddField(
            model_name='logpurchaseadditionalcharge',
            name='charge_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.additionalchargetype'),
        ),
        migrations.AddField(
            model_name='logpurchaseadditionalcharge',
            name='purchase_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchasemaster'),
        ),
        migrations.AddField(
            model_name='logpartypaymentdetail',
            name='party_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='party_payment.partypayment'),
        ),
        migrations.AddField(
            model_name='logpartypaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='logpartypayment',
            name='purchase_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchasemaster'),
        ),
        migrations.AddField(
            model_name='logpartypayment',
            name='ref_party_clearance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='party_payment.partypayment'),
        ),
        migrations.AddField(
            model_name='logpackingtypedetail',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.item'),
        ),
        migrations.AddField(
            model_name='logpackingtypedetail',
            name='packing_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.packingtype'),
        ),
        migrations.AddField(
            model_name='logorganizationsetup',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='blank= True and null= True', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.country'),
        ),
        migrations.AddField(
            model_name='logordermaster',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='logordermaster',
            name='discount_scheme',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.discountscheme'),
        ),
        migrations.AddField(
            model_name='logorderdetail',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.item'),
        ),
        migrations.AddField(
            model_name='logorderdetail',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_order.ordermaster'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='generic_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.genericname'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='item_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemcategory'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.manufacturer'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text=' blank=True, null= True', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.unit'),
        ),
        migrations.AddField(
            model_name='logdistrict',
            name='province',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Fk Province', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.province'),
        ),
        migrations.AddField(
            model_name='logcustompermission',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='null=True, blank=True', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user_group.permissioncategory'),
        ),
        migrations.AddField(
            model_name='logcustomer',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='blank= True and null= True', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.country'),
        ),
        migrations.AddField(
            model_name='logcreditpaymentdetail',
            name='credit_clearance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='credit_management.creditclearance'),
        ),
        migrations.AddField(
            model_name='logcreditpaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='logcreditclearance',
            name='ref_credit_clearance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='credit_management.creditclearance'),
        ),
        migrations.AddField(
            model_name='logcreditclearance',
            name='sale_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.salemaster'),
        ),
        migrations.AddField(
            model_name='logbasicpartypaymentdetail',
            name='basic_party_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='party_payment.basicpartypayment'),
        ),
        migrations.AddField(
            model_name='logbasicpartypaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='logbasicpartypayment',
            name='fiscal_session_ad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.fiscalsessionad'),
        ),
        migrations.AddField(
            model_name='logbasicpartypayment',
            name='fiscal_session_bs',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.fiscalsessionbs'),
        ),
        migrations.AddField(
            model_name='logbasicpartypayment',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='logbankdeposit',
            name='bank',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.bank'),
        ),
        migrations.AddField(
            model_name='logadvanceddepositpaymentdetail',
            name='advanced_deposit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='advance_deposit.advanceddeposit'),
        ),
        migrations.AddField(
            model_name='logadvanceddepositpaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='logadvanceddeposit',
            name='order_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_order.ordermaster'),
        ),
        migrations.AddField(
            model_name='logadvanceddeposit',
            name='sale_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.salemaster'),
        ),
    ]
