# Generated by Django 3.2 on 2023-01-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPartyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('payment_type', models.PositiveIntegerField(choices=[(1, 'PAYMENT'), (2, 'RETURN')], help_text='Payment type like 1=PAYMENT, 2=RETURN')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Maximum value 9999999999.99, min_value=0.0', max_digits=12)),
                ('receipt_no', models.CharField(blank=True, help_text='Receipt no can have max of 20 characters and blank = true', max_length=20, null=True)),
                ('payment_date_ad', models.DateField(help_text='Payment Date AD', max_length=10)),
                ('payment_date_bs', models.CharField(help_text='Payment Date BS', max_length=10)),
                ('remarks', models.CharField(blank=True, help_text='Max upto 100 characters, blank=True', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasicPartyPaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Maximum value 9999999999.99, min_value=0.0', max_digits=12)),
                ('remarks', models.CharField(blank=True, help_text='Max upto 100 characters, blank=True', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('payment_type', models.PositiveIntegerField(choices=[(1, 'PAYMENT'), (2, 'REFUND')], default=0, help_text='Where 1 = PAYMENT, 2 = REFUND')),
                ('receipt_no', models.CharField(help_text='Receipt no can have max of 20 characters', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='max_value upto 9999999999.99 and min_vale=0.0', max_digits=12)),
                ('remarks', models.CharField(blank=True, help_text='Remarks can be max upto 50 characters, blank=True', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartyPaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Maximum value 9999999999.99, min_value=0.0', max_digits=12)),
                ('remarks', models.CharField(blank=True, help_text='Max upto 50 characters, blank=True', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
